"""empty message

Revision ID: 5f77961e1546
Revises: None
Create Date: 2016-02-26 17:43:50.805511

"""

# revision identifiers, used by Alembic.
revision = '5f77961e1546'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=50), nullable=False),
    sa.Column('Password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Username')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=True),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('Tag', sa.String(length=50), nullable=True),
    sa.Column('FileLocation', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_modes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Mode', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=50), nullable=True),
    sa.Column('LastName', sa.String(length=50), nullable=True),
    sa.Column('CardNumber', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=50), nullable=True),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('Mode', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Mode'], ['game_modes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('MemberID', sa.Integer(), nullable=True),
    sa.Column('Date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['MemberID'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('GameDeviceLink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('GameDeviceLink')
    op.drop_table('visits')
    op.drop_table('games')
    op.drop_table('members')
    op.drop_table('game_modes')
    op.drop_table('devices')
    op.drop_table('admin_user')
    ### end Alembic commands ###
